server:
  port: 444
#  http:
#    port: 8888
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    keyStoreType: PKCS12
#    keyAlias: tomcat
#发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
#rocketmq:
##是否开启自动配置
#  isEnable: true
##mq的nameserver地址
#  namesrvAddr: 127.0.0.1:9876
##消息最大长度 默认1024*4(4M)
#  producer:
#    maxMessageSize: 4096
##发送消息超时时间,默认3000
#    sendMsgTimeout: 3000
##发送消息失败重试次数，默认2
#    retryTimesWhenSendFailed: 2
##消费者线程数量
#  consumer:
#    consumeThreadMin: 5
#    consumeThreadMax: 32
##设置一次消费消息的条数，默认为1条
#    consumeMessageBatchMaxSize: 1
value: 555

defined: "{
  a: 'bbb',
  b: 'ccc'}"

github:
  client:
    clientId: a4d76bdca2f20f7a52fd
    clientSecret: 67fa8b1db5aae03d3b098a18a48837096b2ff243
    accessTokenUri: 127.0.0.1:8080/well
    userAuthorizationUri: http://127.0.0.1:8080/well
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user